##################################
# Application / App / Microservice
##################################
application:

  applicationName: review

  # Deployment
  deployment:
    annotations:
      secret.reloader.stakater.com/reload: review-mongodb-creds
    fluentdConfigAnnotations:
      notifications:
        slack:
          webhookURL: https://hooks.slack.com/services/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
          channelName: "#nordmart-gabbar-application-alerts"
        key: "level"
        pattern: "(ERROR|ERR|error|E[A-Z0-9]{4})"
    additionalLabels:
      appCategory: backend
    imagePullSecrets: docker-reg-creds
    env:
      MONGODB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: review-mongodb-creds
            key: mongodb-root-password
    envFrom:
      review-config:
        type: configmap
        nameSuffix: config

    volumes:
      tmp:
        emptyDir: {}

    volumeMounts:
      tmp:
        mountPath: /tmp

    resources:
      limits:
        memory: 1Gi
        cpu: 0.6
      requests:
        memory: 128Mi
        cpu: 0.1

    readinessProbe:
      enabled: true
      failureThreshold: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
      initialDelaySeconds: 15
      httpGet:
        path: /actuator/health
        port: 8080

    livenessProbe:
      enabled: true
      failureThreshold: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
      initialDelaySeconds: 15
      httpGet:
        path: /actuator/health
        port: 8080

  ## Prometheus Rule to trigger alerts based on ratings
  prometheusRule:
    enabled: true
    additionalLabels:
      prometheus: stakater-workload-monitoring
    groups:
      - name: nordmart-review-low-rating-warning
        rules:
          - alert: NordmartReviewLowRatingsCritical
            annotations:
              message: >-
                Total ratings below 2 has crossed the threshold 8. Total reviews: {{ $value }}.
            expr: >
              sum by (namespace) (nordmart_review_ratings_total{rating="2"} or nordmart_review_ratings_total{rating="1"}) > 8
            labels:
              severity: critical

  ## ConfigMap
  configMap:
    enabled: true
    files:
      config:
        DB_NAME: "nordmartDB"
        MONGO_HOST: "review-mongodb"

  ## RBAC
  rbac:
    serviceAccount:
      enabled: true

  ## Service
  service:
    ports:
    - name: http
      port: 8080
      targetPort: 8080

  ## Route
  route:
    enabled: true
    port:
      targetPort: http

  ## Service Monitor
  serviceMonitor:
    enabled: true

  ## Endpoint Montior
  endpointMonitor:
    enabled: true
    # add uptime robot additional config
    additionalConfig:
      uptimeRobotConfig:
        alertContacts: "3514554"
        keywordExists: 'yes'
        keywordValue: '404'
        monitorType: keyword

  externalSecret:
    enabled: true

    # Default SecretStore for all externalsecrets defines which SecretStore to use when fetching the secret data
    secretStore:
      name: tenant-vault-secret-store
      #kind: ClusterSecretStore # Defaults to SecretStore if not specified

    # RefreshInterval is the amount of time before the values reading again from the SecretStore provider
    refreshInterval: "1m"
    files:
    # The full name of secret will be review-mongodb-creds; review it applicationName defined above
      mongodb-creds:
      #Data defines the connection between the Kubernetes Secret keys and the Provider data
        dataFrom:
          key: review-api/dev/mongodb-creds

#####################
# Grafana dashboard
#####################
  grafanaDashboard:
    enabled: false
    contents:
      nordmart-review-statistics-dashboard:
        instanceSelector:
          matchLabels:
            app: review-api
        json: |-
              {
              "annotations": {
                "list": [
                  {
                    "builtIn": 1,
                    "datasource": "-- Grafana --",
                    "enable": true,
                    "hide": true,
                    "iconColor": "rgba(0, 211, 255, 1)",
                    "name": "Annotations & Alerts",
                    "type": "dashboard"
                  }
                ]
              },
              "description": "Dashboard for Nordmart Review Spring Boot2 Statistics(by micrometer-prometheus).",
              "editable": true,
              "gnetId": 6756,
              "graphTooltip": 0,
              "id": 13,
              "iteration": 1652015183031,
              "links": [],
              "panels": [
                {
                  "aliasColors": {},
                  "bars": false,
                  "dashLength": 10,
                  "dashes": false,
                  "datasource": null,
                  "fieldConfig": {
                    "defaults": {},
                    "overrides": []
                  },
                  "fill": 1,
                  "fillGradient": 0,
                  "gridPos": {
                    "h": 9,
                    "w": 24,
                    "x": 0,
                    "y": 0
                  },
                  "hiddenSeries": false,
                  "id": 100,
                  "legend": {
                    "avg": false,
                    "current": false,
                    "max": false,
                    "min": false,
                    "show": true,
                    "total": false,
                    "values": false
                  },
                  "lines": true,
                  "linewidth": 1,
                  "nullPointMode": "null",
                  "options": {
                    "alertThreshold": true
                  },
                  "percentage": false,
                  "pluginVersion": "7.5.15",
                  "pointradius": 2,
                  "points": false,
                  "renderer": "flot",
                  "seriesOverrides": [],
                  "spaceLength": 10,
                  "stack": false,
                  "steppedLine": false,
                  "targets": [
                    {
                      "exemplar": true,
                      "expr": "sum(nordmart_review_ratings_total{namespace=~\"$namespace\"})",
                      "interval": "",
                      "legendFormat": "",
                      "refId": "A"
                    }
                  ],
                  "thresholds": [],
                  "timeFrom": null,
                  "timeRegions": [],
                  "timeShift": null,
                  "title": "Total Ratings Submitted Over Time",
                  "tooltip": {
                    "shared": true,
                    "sort": 0,
                    "value_type": "individual"
                  },
                  "type": "graph",
                  "xaxis": {
                    "buckets": null,
                    "mode": "time",
                    "name": null,
                    "show": true,
                    "values": []
                  },
                  "yaxes": [
                    {
                      "format": "short",
                      "label": null,
                      "logBase": 1,
                      "max": null,
                      "min": null,
                      "show": true
                    },
                    {
                      "format": "short",
                      "label": null,
                      "logBase": 1,
                      "max": null,
                      "min": null,
                      "show": true
                    }
                  ],
                  "yaxis": {
                    "align": false,
                    "alignLevel": null
                  }
                },
                {
                  "aliasColors": {},
                  "bars": false,
                  "dashLength": 10,
                  "dashes": false,
                  "datasource": null,
                  "fieldConfig": {
                    "defaults": {},
                    "overrides": []
                  },
                  "fill": 1,
                  "fillGradient": 0,
                  "gridPos": {
                    "h": 8,
                    "w": 12,
                    "x": 0,
                    "y": 9
                  },
                  "hiddenSeries": false,
                  "id": 102,
                  "legend": {
                    "avg": false,
                    "current": false,
                    "max": false,
                    "min": false,
                    "show": true,
                    "total": false,
                    "values": false
                  },
                  "lines": true,
                  "linewidth": 1,
                  "nullPointMode": "null",
                  "options": {
                    "alertThreshold": true
                  },
                  "percentage": false,
                  "pluginVersion": "7.5.15",
                  "pointradius": 2,
                  "points": false,
                  "renderer": "flot",
                  "seriesOverrides": [],
                  "spaceLength": 10,
                  "stack": false,
                  "steppedLine": false,
                  "targets": [
                    {
                      "exemplar": true,
                      "expr": "sum by (rating) (nordmart_review_ratings_total{namespace=~\"$namespace\"})",
                      "interval": "",
                      "legendFormat": "",
                      "refId": "A"
                    }
                  ],
                  "thresholds": [],
                  "timeFrom": null,
                  "timeRegions": [],
                  "timeShift": null,
                  "title": "Total Ratings For Each Rating Type Over Time",
                  "tooltip": {
                    "shared": true,
                    "sort": 0,
                    "value_type": "individual"
                  },
                  "type": "graph",
                  "xaxis": {
                    "buckets": null,
                    "mode": "time",
                    "name": null,
                    "show": true,
                    "values": []
                  },
                  "yaxes": [
                    {
                      "format": "short",
                      "label": null,
                      "logBase": 1,
                      "max": null,
                      "min": null,
                      "show": true
                    },
                    {
                      "format": "short",
                      "label": null,
                      "logBase": 1,
                      "max": null,
                      "min": null,
                      "show": true
                    }
                  ],
                  "yaxis": {
                    "align": false,
                    "alignLevel": null
                  }
                },
                {
                  "datasource": null,
                  "fieldConfig": {
                    "defaults": {
                      "color": {
                        "mode": "thresholds"
                      },
                      "mappings": [],
                      "thresholds": {
                        "mode": "absolute",
                        "steps": [
                          {
                            "color": "green",
                            "value": null
                          },
                          {
                            "color": "red",
                            "value": 80
                          }
                        ]
                      }
                    },
                    "overrides": []
                  },
                  "gridPos": {
                    "h": 8,
                    "w": 12,
                    "x": 12,
                    "y": 9
                  },
                  "id": 101,
                  "options": {
                    "displayMode": "gradient",
                    "orientation": "auto",
                    "reduceOptions": {
                      "calcs": [
                        "lastNotNull"
                      ],
                      "fields": "",
                      "values": false
                    },
                    "showUnfilled": true,
                    "text": {}
                  },
                  "pluginVersion": "7.5.15",
                  "targets": [
                    {
                      "exemplar": true,
                      "expr": "sum by (rating) (nordmart_review_ratings_total{namespace=~\"$namespace\"})",
                      "interval": "",
                      "legendFormat": "",
                      "refId": "A"
                    }
                  ],
                  "timeFrom": null,
                  "timeShift": null,
                  "title": "Total Ratings For Each Rating Type",
                  "type": "bargauge"
                }
              ],
              "refresh": false,
              "schemaVersion": 27,
              "style": "dark",
              "tags": [],
              "templating": {
                "list": [
                  {
                    "allValue": null,
                    "current": {
                      "selected": false,
                      "text": "{{ .Release.Namespace | replace "-dev" "" | replace "-build" "" | replace "-test" "" }}-dev",
                      "value": "{{ .Release.Namespace | replace "-dev" "" | replace "-build" "" | replace "-test" "" }}-dev"
                    },
                    "datasource": null,
                    "definition": "label_values(kube_pod_info, namespace)",
                    "description": null,
                    "error": null,
                    "hide": 0,
                    "includeAll": false,
                    "label": "Namespace",
                    "multi": false,
                    "name": "namespace",
                    "options": [
                      {
                        "selected": false,
                        "text": "{{ .Release.Namespace | replace "-dev" "" | replace "-build" "" | replace "-test" "" }}-build",
                        "value": "{{ .Release.Namespace | replace "-dev" "" | replace "-build" "" | replace "-test" "" }}-build"
                      },
                      {
                        "selected": true,
                        "text": "{{ .Release.Namespace | replace "-dev" "" | replace "-build" "" | replace "-test" "" }}-dev",
                        "value": "{{ .Release.Namespace | replace "-dev" "" | replace "-build" "" | replace "-test" "" }}-dev"
                      }
                    ],
                    "query": {
                      "query": "label_values(kube_pod_info, namespace)",
                      "refId": "StandardVariableQuery"
                    },
                    "refresh": 0,
                    "regex": "/.*{{ .Release.Namespace | replace "-dev" "" | replace "-build" "" | replace "-test" "" }}.*/",
                    "skipUrlSync": false,
                    "sort": 5,
                    "tagValuesQuery": "",
                    "tags": [],
                    "tagsQuery": "",
                    "type": "query",
                    "useTags": false
                  }
                ]
              },
              "time": {
                "from": "now-5m",
                "to": "now"
              },
              "timepicker": {
                "refresh_intervals": [
                  "5s",
                  "10s",
                  "30s",
                  "1m",
                  "5m",
                  "15m",
                  "30m",
                  "1h",
                  "2h",
                  "1d"
                ],
                "time_options": [
                  "5m",
                  "15m",
                  "1h",
                  "6h",
                  "12h",
                  "24h",
                  "2d",
                  "7d",
                  "30d"
                ]
              },
              "timezone": "",
              "title": "Nordmart-Review Ratings Statistics",
              "version": 23 }       
#####################
# MongoDB dependency
#####################
mongodb:

  fullnameOverride: review-mongodb

  updateStrategy:
    type: Recreate

  resources:
     limits:
       memory: 1Gi
       cpu: 0.5
     requests:
       memory: 128Mi
       cpu: 0.1

  auth:
    enabled: true
    # Its created via an external secret from vault; defined above
    existingSecret: review-mongodb-creds

  podSecurityContext:
    enabled: false

  containerSecurityContext:
    enabled: false


