##################################
# Application / App / Microservice
##################################
application:

  applicationName: review

  # Deployment
  deployment:
    annotations:
      secret.reloader.stakater.com/reload: review-mongodb-creds
    fluentdConfigAnnotations:
      notifications:
        slack:
          webhookURL: https://hooks.slack.com/services/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
          channelName: "#nordmart-gabbar-application-alerts"
        key: "level"
        pattern: "(ERROR|ERR|error|E[A-Z0-9]{4})"
    additionalLabels:
      appCategory: backend
    imagePullSecrets: docker-reg-creds
    env:
      MONGODB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: review-mongodb-creds
            key: mongodb-root-password
    envFrom:
      review-config:
        type: configmap
        nameSuffix: config

    volumes:
      tmp:
        emptyDir: {}

    volumeMounts:
      tmp:
        mountPath: /tmp

    resources:
      limits:
        memory: 1Gi
        cpu: 0.6
      requests:
        memory: 128Mi
        cpu: 0.1

    readinessProbe:
      enabled: true
      failureThreshold: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
      initialDelaySeconds: 15
      httpGet:
        path: /actuator/health
        port: 8080

    livenessProbe:
      enabled: true
      failureThreshold: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
      initialDelaySeconds: 15
      httpGet:
        path: /actuator/health
        port: 8080

  ## Prometheus Rule to trigger alerts based on ratings
  prometheusRule:
    enabled: true
    additionalLabels:
      prometheus: stakater-workload-monitoring
    groups:
      - name: nordmart-review-low-rating-warning
        rules:
          - alert: NordmartReviewLowRatingsCritical
            annotations:
              message: >-
                Total ratings below 2 has crossed the threshold 8. Total reviews: {{ $value }}.
            expr: >
              sum by (namespace) (nordmart_review_ratings_total{rating="2"} or nordmart_review_ratings_total{rating="1"}) > 8
            labels:
              severity: critical

  ## ConfigMap
  configMap:
    enabled: true
    files:
      config:
        DB_NAME: "nordmartDB"
        MONGO_HOST: "review-mongodb"

  ## RBAC
  rbac:
    serviceAccount:
      enabled: true

  ## Service
  service:
    ports:
    - name: http
      port: 8080
      targetPort: 8080

  ## Route
  route:
    enabled: true
    port:
      targetPort: http

  ## Service Monitor
  serviceMonitor:
    enabled: true

  ## Endpoint Montior
  endpointMonitor:
    enabled: true
    # add uptime robot additional config
    additionalConfig:
      uptimeRobotConfig:
        alertContacts: "3514554"
        keywordExists: 'yes'
        keywordValue: '404'
        monitorType: keyword

  externalSecret:
    enabled: true

    # Default SecretStore for all externalsecrets defines which SecretStore to use when fetching the secret data
    secretStore:
      name: tenant-vault-secret-store
      #kind: ClusterSecretStore # Defaults to SecretStore if not specified

    # RefreshInterval is the amount of time before the values reading again from the SecretStore provider
    refreshInterval: "1m"
    files:
    # The full name of secret will be review-mongodb-creds; review it applicationName defined above
      mongodb-creds:
      #Data defines the connection between the Kubernetes Secret keys and the Provider data
        dataFrom:
          key: review-api/dev/mongodb-creds

#####################
# MongoDB dependency
#####################
mongodb:

  fullnameOverride: review-mongodb

  updateStrategy:
    type: Recreate

  resources:
     limits:
       memory: 1Gi
       cpu: 0.5
     requests:
       memory: 128Mi
       cpu: 0.1

  auth:
    enabled: true
    # Its created via an external secret from vault; defined above
    existingSecret: review-mongodb-creds

  podSecurityContext:
    enabled: false

  containerSecurityContext:
    enabled: false

#####################
# Grafana dashboard
#####################
grafanaDashboard:
  enabled: true
