name: Sync Changes to Another Repo

on:
  pull_request:
    branches:
      - main
    paths:
      - '.tekton/git_clone.yaml'

jobs:
  sync-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "stakater@gmail.com"
          git config --global user.name "stakater-user"

      - name: Sync Changes to Another Repo
        env:
          GH_TOKEN: ${{ secrets.NORDMARTTESTZONE_GITHUB_TOKEN }}
        run: |
            IFS='/' read -ra REPO_INFO <<< "$GITHUB_REPOSITORY"
            SOURCE_OWNER="${REPO_INFO[0]}"
            SOURCE_REPO="${REPO_INFO[1]}"
            
            # Target Repository
            TARGET_OWNER="NordMartTestZone"
            TARGET_REPO="review-api"
            TARGET_BRANCH="main" # Change this to the target branch in the other repository
            
            # Create a new branch for the changes in the target repository
            BRANCH_NAME="sync-changes-${GITHUB_RUN_NUMBER}"
            git checkout -b "$BRANCH_NAME"

            # Commit changes to the target repository
            git add ./tekton/git_clone.yaml
            git commit -am "Sync changes from $SOURCE_OWNER/$SOURCE_REPO:${GITHUB_SHA}"
            git push origin "$BRANCH_NAME"

            # Create a pull request using gh CLI
            gh pr create --base "$TARGET_BRANCH" --head "$TARGET_OWNER:$BRANCH_NAME" --title "Sync changes from $SOURCE_OWNER/$SOURCE_REPO" --body "Sync changes from $SOURCE_OWNER/$SOURCE_REPO:${GITHUB_SHA}"
