on:
  push:
    branches:
      - main
    paths:
    - '.tekton/**'
    tags-ignore:
      - "**"

name: on-change-in-tekton-pipeline

jobs:
  send-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0 # Checkout everything to get access to the tags
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files in .tekton directory
        id: get_changed_files
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^\.tekton/")
          IFS=$'\n' read -rd '' -a files_array <<<"$changed_files"

      - name: Process filenames
        id: process_filenames
        run: |
          processed_files=()
          for file in "${files_array[@]}"; do
            # Remove file extension
            file_name="${file%.*}"
            # Replace underscores with hyphens
            processed_file_name="${file_name//_/-}"
            processed_files+=("$processed_file_name")
          done

      - name: Display processed filenames
        run: echo "${processed_files[@]}"

      - name: Send pull-request
        run: |
          LATEST_TAG=$(git describe --tags --always --abbrev=0)
          REPOSITORY="stakater/saap-docs"
          FOLDER="bin/$REPOSITORY"
          BRANCH_NAME="Auto-Update-Pipeline-Docs-$(openssl rand -hex 2)"

          # Clone the remote repository and change working directory to the
          # folder it was cloned to.
          git clone \
            --depth=1 \
            --branch=main \
            https://stakater-nordmart-bot:${{ secrets.STAKATER_GITHUB_TOKEN }}@github.com/$REPOSITORY \
            $FOLDER

          cd $FOLDER

          # Setup the committers identity.
          git config  user.email "stakater@gmail.com"
          git config  user.name "stakater-user"

          # Create a new feature branch for the changes.
          git checkout -b $BRANCH_NAME
          
          git config user.name
          git config user.email

          
          # Update Changelog
          echo -e "Pipelines updated.\n${processed_files[@]}" >> CHANGELOG.md

          # Commit the changes and push the feature branch to origin
          git add .
          git commit -m "Update pipeline yamls"
          git push origin $BRANCH_NAME

          # Store the PAT in a file that can be accessed by the
          # GitHub CLI.
          echo "${{ secrets.STAKATER_GITHUB_TOKEN }}" > token.txt

          # Authorize GitHub CLI for the current repository and
          # create a pull-requests containing the updates.
          gh auth login --with-token < token.txt
          echo "Updating Docs"
          gh pr create \
            --body "" \
            --title "Update pipeline yamls" \
            --head "$BRANCH_NAME" \
            --base "main"

